# Generated by Django 2.2.7 on 2019-11-11 08:31

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busroutes', '0016_auto_20191107_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), srid=4326),
        ),
    ]
