# Generated by Django 2.2.7 on 2020-03-09 06:24

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busroutes', '0017_stage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_hindi', models.CharField(max_length=64)),
                ('wiki_link', models.URLField()),
                ('station_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), srid=4326)),
                ('notes', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Metro Station',
                'verbose_name_plural': 'Metro Stations',
            },
        ),
    ]
