# Generated by Django 2.2.7 on 2020-07-04 06:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busroutes', '0020_routeactivityfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('notification', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fcm_options', django.contrib.postgres.fields.jsonb.JSONField()),
                ('channel_id', models.TextField(blank=True, max_length=1000, null=True)),
                ('topic', models.CharField(blank=True, max_length=250, null=True)),
                ('tokens', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firebase Notification',
                'verbose_name_plural': 'Firebase Notifications',
            },
        ),
        migrations.CreateModel(
            name='FirebaseTopicSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firebase Topic Subscription',
                'verbose_name_plural': 'Firebase Topic Subscription',
                'unique_together': {('instance_id', 'topic')},
            },
        ),
    ]
