# Generated by Django 2.2.7 on 2025-06-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busroutes', '0021_firebasenotification_firebasetopicsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='coordinates',
        ),
    ]
