# Generated by Django 5.2.1 on 2025-06-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busroutes', '0022_remove_stage_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasenotification',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='firebasenotification',
            name='fcm_options',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='firebasenotification',
            name='notification',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='firebasenotification',
            name='tokens',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='station_details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='stages',
            field=models.ManyToManyField(through='busroutes.StageSequence', through_fields=('route', 'stage'), to='busroutes.stage'),
        ),
    ]
